### ISSUE TITLE
Plans to merge into main trufflehog

### ISSUE THREAD

**Issue by dxa4481** [feeltheajf/trufflehog3#24]
Hey there,

Just wanted to give you a heads up, I plan to merge trufflehog3 into trufflehog. Thanks for making these awesome features, let me know if you have any thoughts.

-d

**Comment by feeltheajf** [comment]
Hi @dxa4481 

Impressive news! I'd like to note that there's ongoing work on `yet-again-from-scratch` v3, you can have a sneak peak at a sample HTML report (any suggestions are welcome)

https://github.com/feeltheajf/trufflehog3/blob/master/examples/report.html 

Unfortunately, due to high load at my primary place of work, I will not be able to finish it in 1-2 months. All I can do right now is push all the code to gh for you to have a look.
