### ISSUE TITLE
Trufflehog no longer detects certain passwords

### ISSUE THREAD

**Issue by commjoen** [feeltheajf/trufflehog3#37]
Hi there!
First of all, thank you very much for this great tool! It has helped a lot for many of my secret-hunting. In one of the latest versions it all of all sudden does not see this as a secret, while it used to detect this as a secret:

```json
{
      "mode": "managed",
      "type": "random_password",
      "name": "password",
      "provider": "provider[\"registry.terraform.io/hashicorp/random\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "none",
            "keepers": null,
            "length": 24,
            "lower": true,
            "min_lower": 0,
            "min_numeric": 0,
            "min_special": 0,
            "min_upper": 0,
            "number": true,
            "override_special": "_%@",
            "result": "9o_UoiNX7fETqY5EWOk03_pK",
            "special": true,
            "upper": true
          },
          "sensitive_attributes": [],
          "private": "bnVsbA=="
        }
      ]
    },
```

How did I get here?
- Install trufflehog3: `pip install trufflehog3`
- follow instructions at https://github.com/commjoen/wrongsecrets/blob/master/aws/README.md 
- follow instructions at http://localhost:8080/challenge/9

Then normally the secret above ends up in the `terraform-infra.json` but that no longer does.

**Comment by feeltheajf** [comment]
Hey @commjoen 

This is probably due to increased minimum required length for high entropy findings. Unfortunately, high entropy check brings lots of false positives, which is why at some point the lower length bound was increased up to 20 characters. In addition, the underscore symbol is not included in the default alphabet once again due to FPs in function names, etc. 

What you can do is copy the [rules.yml](https://github.com/feeltheajf/trufflehog3/blob/master/trufflehog3/static/rules.yml), make any changes and then pass it to trufflehog via `-r/--rules` option.

**Comment by commjoen** [comment]
Thank you :-)
